name: lia_lectura_inmersiva
description: Una app de lectura inmersiva con audio y voz reactiva.
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  speech_to_text: ^7.0.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  lottie: ^2.6.0
  rive: ^0.13.0
  permission_handler: ^11.0.1
  flutter_animate: ^4.2.0
  string_similarity: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  
    - assets/images/portada_ditox.png
    - assets/images/portada_gadianes.png
    - assets/images/portada_artefactos.png
    - assets/images/fondo_saga_blur.png
    - assets/images/fondo_lector.png
    - assets/images/fondo_lector1.2.png
    - assets/images/splash_lia.png
    - assets/images/icono_lia.png
    - assets/images/libro_icono.png
    - assets/images/efecto_artefacto.png
    - assets/images/efecto_laboratorio.png
    - assets/images/efecto_sombra.png

    - assets/data/escenas.json
    - assets/data/escenas_completas.json

    - assets/portadas/libro1.png
    - assets/portadas/libro2.png
    - assets/portadas/libro3.png


    - assets/audio/musica_futurista.mp3
    - assets/sounds/siguiente_pagina.mp3  # AÑADIDO para sonido al pasar página
    - assets/rive/
    - assets/sounds/tap_confirm.mp3
    - assets/animations/logo_lia.json

    - assets/animaciones/abuelo_abelard.png
    - assets/animaciones/angelo_boutov.png
    - assets/animaciones/artefacto.png
    - assets/animaciones/brazalete.png
    - assets/animaciones/cristal.png
    - assets/animaciones/daga.png
    - assets/animaciones/diario.png
    - assets/animaciones/khoorx.png
    - assets/animaciones/laboratorio.png
    - assets/animaciones/medallon.png
    - assets/animaciones/rayo.png
    - assets/animaciones/reliquia.png
    - assets/animaciones/sargento_silvano.png
    - assets/animaciones/sombra.png
    - assets/animaciones/toxina.png
    - assets/animaciones/reliquias_familiares.png
    - assets/animaciones/obras_de_teatro.png
    - assets/animaciones/mascara_antigas.png
    - assets/animaciones/imagen_misma_de_los_cielos.png
    - assets/animaciones/auto_convertible.png
    - assets/animaciones/rachel.png
    - assets/animaciones/jefe_akinae.png
    - assets/animaciones/el_resguardo.png
    - assets/animaciones/darien.png
    - assets/animaciones/doce_artefactos.png
    - assets/animaciones/akineanos.png
    - assets/animaciones/gadianes.png
    - assets/animaciones/khimm.png
    - assets/animaciones/augusto.png
    - assets/animaciones/anastasia.png
    - assets/animaciones/gibran.png
    - assets/animaciones/augusto.png
    - assets/animaciones/lindsay.png


    - assets/sounds/abuelo_abelard.mp3
    - assets/sounds/angelo_boutov.mp3
    - assets/sounds/artefacto.mp3
    - assets/sounds/brazalete.mp3
    - assets/sounds/cristal.mp3
    - assets/sounds/daga.mp3
    - assets/sounds/diario.mp3
    - assets/sounds/khoorx.mp3
    - assets/sounds/laboratorio.mp3
    - assets/sounds/medallon.mp3
    - assets/sounds/rayo.mp3
    - assets/sounds/reliquia.mp3
    - assets/sounds/sargento_silvano.mp3
    - assets/sounds/sombra.mp3
    - assets/sounds/toxina.mp3
    - assets/sounds/reliquias_familiares.mp3
    - assets/sounds/obras_de_teatro.mp3
    - assets/sounds/imagen_misma_de_los_cielos.mp3
    - assets/sounds/mascara_antigas.mp3
    - assets/sounds/auto_convertible.mp3
    - assets/sounds/rachel.mp3
    - assets/sounds/jefe_akinae.mp3
    - assets/sounds/el_resguardo.mp3
    - assets/sounds/darien.mp3
    - assets/sounds/doce_artefactos.mp3
    - assets/sounds/akineanos.mp3
    - assets/sounds/gadianes.mp3
    - assets/sounds/khimm.mp3
    - assets/sounds/augusto.mp3
    - assets/sounds/anastasia.mp3
    - assets/sounds/gibran.mp3
    - assets/sounds/augusto.mp3
    - assets/sounds/lindsay.mp3
